### ISSUE TITLE
ImportError: No module named 'tf_ctpn.lib'

### ISSUE THREAD

**Issue by zkailinzhang** [Sanster/DeepOcrService#3]
run app.py, following error:
Traceback (most recent call last):
  File "F:/1zklcode/python/ocr/DeepOcrService/app.py", line 10, in <module>
    from detector import Detector
  File "F:\1zklcode\python\ocr\DeepOcrService\detector.py", line 14, in <module>
    from tf_ctpn.lib.text_connector import TextDetector
ImportError: No module named 'tf_ctpn.lib'

and then ,
cd tf_ctpn/lib && make
bash: cd: tf_ctpn/lib: No such file or directory

tf_ctpn directory  is empty

**Comment by zkailinzhang** [comment]
tensorflow.gpu
